[package]
name = "waygriff"
version = "0.1.0"
edition = "2024"

[profile.release]
overflow-checks = true

[profile.ricemax]
inherits = "release"
opt-level = 3
lto = "fat"
codegen-units = 1

[dependencies]
anyhow = { version = "1.0.101", features = ["backtrace"] }
arc-swap = "1.8.2"
ash = "0.38.0"
bytemuck = "1.25.0"
clap = { version = "4.5.58", features = ["derive"] }
copypasta = "0.10.2"
crossterm = "0.29.0"
cudarc = { version = "0.19.2", features = ["cuda-version-from-build-system"] }
drm-fourcc = "2.2.0"
humantime = "2.3.0"
image = "0.25.9"
itertools = "0.14.0"
nix = { version = "0.31.1", features = ["fs", "time"] }
pollster = "0.4.0"
ratatui = "0.30.0"
ratatui-widgets = "0.3.0"
reis = { version = "0.6.0", features = ["calloop"] }
smallvec = "1.15.1"
smithay = { version = "0.7.0", default-features = false, features = ["wayland_frontend", "backend_drm"] }
smithay-client-toolkit = "0.20.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
vello = "0.7.0"
viuer = "0.11.0"
vulkano = "0.35.2"
vulkano-shaders = "0.35.0"
winit = "0.30.12"
x11rb = { version = "0.13.2", features = ["xtest"] }

[build-dependencies]
cc = "1.2.56"
