[package]
name = "waygriff"
version = "0.1.0"
edition = "2024"

[profile.release]
overflow-checks = true

[profile.ricemax]
inherits = "release"
opt-level = 3
lto = "fat"
codegen-units = 1

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
arc-swap = "1.8.0"
ash = "0.38.0"
bytemuck = "1.24.0"
clap = { version = "4.5.54", features = ["derive"] }
copypasta = "0.10.2"
crossterm = "0.29.0"
cudarc = { version = "0.19.0", features = ["cuda-version-from-build-system"] }
drm-fourcc = "2.2.0"
humantime = "2.3.0"
image = "0.25.9"
itertools = "0.14.0"
nix = { version = "0.31.1", features = ["fs"] }
ratatui = "0.30.0"
ratatui-widgets = "0.3.0"
smallvec = "1.15.1"
smithay-client-toolkit = "0.20.0"
thiserror = "2.0.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
viuer = "0.11.0"
vulkano = "0.35.2"
vulkano-shaders = "0.35.0"
wayland-backend = { version = "0.3.12", features = ["client_system"] }
x11rb = { version = "0.13.2", features = ["xtest"] }

[build-dependencies]
cc = "1.2.54"
